[build]
rustflags = [
    "--codegen",
    "force-frame-pointers=yes",
    "--codegen",
    "relocation-model=dynamic-no-pic",
    "--codegen",
    "debuginfo=full",
]
target = "kernel.json"

[target.'cfg(target_os = "none")']
runner = "./scripts/run_kernel.sh"

[unstable]
build-std = ["alloc", "compiler_builtins", "core"]
