binop_separator = "Back"
chain_width = 80
combine_control_expr = false
comment_width = 100
condense_wildcard_suffixes = true
empty_item_single_line = false
fn_params_layout = "Vertical"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Upper"
imports_granularity = "Crate"
imports_layout = "Vertical"
match_arm_blocks = false
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
short_array_element_width_threshold = 1
single_line_if_else_max_width = 1
spaces_around_ranges = true
struct_variant_width = 0
use_field_init_shorthand = true
